# Generated by Django 6.0.3 on 2026-04-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_plant_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='is_edible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plants/images'),
        ),
    ]
