# Generated by Django 6.0.3 on 2026-04-20 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_plant_is_edible_alter_plant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='category',
            field=models.CharField(choices=[('Fruit', 'Fruit'), ('Vegetable', 'Vegetable'), ('Flower', 'Flower'), ('Tree', 'Tree')], default='Fruit', max_length=20),
        ),
    ]
