# Generated by Django 6.0.3 on 2026-04-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='Anonymous', max_length=200),
            preserve_default=False,
        ),
    ]
